"""add dates

Revision ID: 27b403a113ae
Revises: 17f05dd4a71a
Create Date: 2024-01-17 15:44:45.810928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b403a113ae'
down_revision: Union[str, None] = '17f05dd4a71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('grades', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('grades', 'date')
    # ### end Alembic commands ###
