"""lsdkjf

Revision ID: 3e613fa80e7f
Revises: ec26466355a8
Create Date: 2024-01-17 15:33:47.715176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e613fa80e7f'
down_revision: Union[str, None] = 'ec26466355a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.drop_table('users_subjects')
    op.add_column('grades', sa.Column('enrollment_id', sa.Integer(), nullable=True))
    op.drop_constraint('grades_user_id_fkey', 'grades', type_='foreignkey')
    op.drop_constraint('grades_subject_id_fkey', 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'enrollments', ['enrollment_id'], ['enrollment_id'])
    op.drop_column('grades', 'user_id')
    op.drop_column('grades', 'subject_id')
    op.drop_column('grades', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key('grades_subject_id_fkey', 'grades', 'subjects', ['subject_id'], ['subject_id'])
    op.create_foreign_key('grades_user_id_fkey', 'grades', 'users', ['user_id'], ['user_id'])
    op.drop_column('grades', 'enrollment_id')
    op.create_table('users_subjects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name='users_subjects_subject_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='users_subjects_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_subjects_pkey')
    )
    op.drop_table('enrollments')
    # ### end Alembic commands ###
