"""auto create 'created_at' field

Revision ID: 715aac2fd6a9
Revises: 81a0766e8eae
Create Date: 2024-01-17 21:40:36.138335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715aac2fd6a9'
down_revision: Union[str, None] = '81a0766e8eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
