"""change column names

Revision ID: 857a7e580e20
Revises: 2db1975e00df
Create Date: 2024-01-24 21:14:06.117932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857a7e580e20'
down_revision: Union[str, None] = '2db1975e00df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('grade_value', sa.Integer(), nullable=True))
    op.add_column('grades', sa.Column('grade_date', sa.Date(), nullable=True))
    op.drop_column('grades', 'grade')
    op.drop_column('grades', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('grades', 'grade_date')
    op.drop_column('grades', 'grade_value')
    # ### end Alembic commands ###
